### ISSUE TITLE
don't do npm install all the time

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.installer#1]
when we update we currently run npm install for all packages. This takes a ling time and is often unnecessary. Better to use a `npm list --depth 1 --json` as in https://github.com/LivelyKernel/LivelyKernel/blob/master/bin/helper/check-modules.js and only install the necessary stuff.

**Comment by tylervernonsmith** [comment]
Resolved as of 80cf6ebffa8e814e1e4c6fec1d53c6a599db2085
